name: Deploy to Remote Server without Git

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Compress project
        run: tar --warning=no-file-changed -czf inventory.tar.gz . || true

      - name: Copy project to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          source: "inventory.tar.gz"
          target: "~/"

      - name: Deploy on server
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            # Stop and remove old container & volumes
            docker rm -f inventory || true
            docker volume prune -f || true

            # Remove old folder & recreate
            rm -rf ~/docker/inventory/inventory
            mkdir -p ~/docker/inventory/inventory

            # Extract new code
            tar -xzf ~/inventory.tar.gz -C ~/docker/inventory/inventory
            rm ~/inventory.tar.gz

            # Build & start fresh containers
            cd ~/docker/inventory/inventory
            docker compose up -d --build